#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-gender
Version  : 1.1.0
Release  : 2
URL      : https://pecl.php.net//get/gender-1.1.0.tgz
Source0  : https://pecl.php.net//get/gender-1.1.0.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: php-gender-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
Gender PHP Extension
Synopsis
========
<?php
$gender = new Gender("compress.bzip2:///home/user/nam_dict.txt.bz2");

%package lib
Summary: lib components for the php-gender package.
Group: Libraries

%description lib
lib components for the php-gender package.


%prep
%setup -q -n gender-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20180731/gender.so
